filesService:
  port: :4000

storage:
  filesDir: ./data/images

processingService:
  resizePower: 4
  workerPoolSize: 4

rabbitmq:
  host: rabbit1
  user: test
  password: secret
  addr: :5672
  queueName: processing
