filesService:
  port: :4000
  # fileSizeLimit: 10mb

storage:
  filesDir: ./data/images

processingService:
  resizePower: 4

rabbitmq:
  host: rabbit1
  user: test
  password: secret
  addr: :5672
  queueName: processing
