openapi: 3.0.0
info:
  title: API documentation
  version: 1.0.0

servers:
  - url: http://localhost:4000/api/v1/

paths:
  /image:
    post:
      summary: "uploads images to the server"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
            encoding:
              profileImage:
                contentType: image/png, image/jpeg
      responses:
        200:
          description: "Image uploaded successfully"
          content:
            text/plain:
              schema:
                type: string
        400:
          description: "Bad Request"
          content:
            text/plain:
              schema:
                type: string
        405:
          description: "Unsupported Media Type"
          content:
            text/plain:
              schema:
                type: string
        413:
          description: "Request Entity Too Large"
          content:
            text/plain:
              schema:
                type: string
        500:
          description: "Internal Server Error"
          content:
            text/plain:
              schema:
                type: string
